UPDATE EMP
set HIREDATE = '2025-12-31'
WHERE EMPNO = 7369 

UPDATE EMP 
set HIREDATE = CASE EMPNO
	WHEN 7566 THEN '2025-04-30'
	WHEN 7698 THEN '2025-06-01'
	ELSE HIREDATE
END
WHERE EMPNO IN (7566, 7698)

-- 1st QUESTION
SELECT *
FROM EMP;

SELECT * FROM DEPT

-- 2nd Question
SELECT ENAME,JOB 
FROM EMP WHERE DEPTNO = 30

-- 3rd Question
SELECT ENAME, EMPNO, DEPTNO 
FROM EMP WHERE JOB = 'CLERK'

-- 4th Question
SELECT DEPTNO,DNAME
FROM DEPT WHERE DEPTNO > 20

-- 5th Question
SELECT ENAME 
FROM EMP WHERE COMM > SAL

-- 6th Question
SELECT ENAME 
FROM EMP WHERE COMM > 0.6 * SAL

-- 7th Question
SELECT ENAME, JOB, SAL 
FROM EMP WHERE DEPTNO = 20 AND SAL > 2000

-- 8th Question
SELECT ENAME, JOB, SAL 
FROM EMP WHERE JOB = 'SALESMAN' AND DEPTNO = 30 AND SAL > 1500

-- 9th Question
SELECT ENAME, JOB, SAL 
FROM EMP WHERE JOB = 'MANAGER' OR JOB = 'PRESIDENT'

-- 10th Question
SELECT ENAME, JOB, DEPTNO 
FROM EMP WHERE JOB = 'MANAGER' AND DEPTNO != 30 

-- 11th Question
SELECT * 
FROM EMP WHERE (JOB = 'MANAGER' OR JOB = 'CLERK') AND DEPTNO = 10 

-- 12th Question
SELECT * 
FROM EMP 
WHERE JOB = 'MANAGER' OR (JOB = 'CLERK' AND DEPTNO = 20) 

-- 13th Question
SELECT * 
FROM EMP 
WHERE (JOB = 'MANAGER' AND DEPTNO = 10)
   OR (JOB = 'CLERK' AND DEPTNO = 20)
   OR ((JOB <> 'MANAGER' AND JOB <> 'CLERK') AND SAL > 2000)

-- 14th Question
SELECT * 
FROM EMP 
WHERE DEPTNO = 20 
  AND (JOB <> 'MANAGER' AND JOB <> 'CLERK')

-- 15th Question
SELECT ENAME, SAL 
FROM EMP 
WHERE SAL BETWEEN 1200 AND 1400

-- 16th Question
SELECT ENAME, JOB 
FROM EMP 
WHERE JOB <> 'MANAGER' 
  AND JOB <> 'PRESIDENT'

-- 17th Question
SELECT ENAME, JOB
FROM EMP 
WHERE JOB NOT IN('CLERK', 'ANALYST', 'SALESMAN')

-- 18th Question
SELECT ENAME, COMM 
FROM EMP 
WHERE COMM IS NULL

-- 19th Question
SELECT ENAME, JOB, COMM 
FROM EMP
WHERE COMM IS NOT NULL

-- 20th Question
SELECT ENAME, COMM 
FROM EMP
WHERE (COMM IS NULL) OR (COMM < 100) 

-- 21th Question
SELECT 
	ENAME,
	SAL,
	COMM,
	CASE 
		WHEN COMM IS NULL OR COMM = 0 THEN SAL + 250
		ELSE SAL + COMM
	END AS NET_EARNINGS
FROM EMP
ORDER BY NET_EARNINGS DESC;

-- 22nd Question
SELECT * 
FROM EMP 
WHERE (SAL+ISNULL(COMM,0)) > 2000

-- 23rd Question
SELECT * 
FROM EMP 
WHERE ENAME LIKE 'M%'
   OR ENAME LIKE '%M'

-- 24th Question
SELECT * 
FROM EMP 
WHERE ENAME LIKE '%M%'

-- 25th Question
SELECT *
FROM EMP 
WHERE LEN(ENAME) <= 15 AND ENAME LIKE '__R%' 

-- 26th Question
SELECT * 
FROM EMP
WHERE MONTH(HIREDATE) = 02

-- 27th Question
SELECT * 
FROM EMP
WHERE HIREDATE = EOMONTH(HIREDATE)

-- 28th Question

-- 29th Question
SELECT * 
FROM EMP
WHERE JOB = 'MANAGER' AND YEAR(HIREDATE) = 2003

-- 30th Question

-- 31st Question

-- 32nd Question

-- 33rd Question
SELECT
	ENAME
FROM EMP
WHERE LEFT(ENAME, 1) <> 'A'

-- 34th Question
SELECT
	ENAME
FROM EMP
WHERE RIGHT(ENAME, 1) <> 'R'

-- 35th Question
SELECT 
	ENAME,
	LEFT(ENAME, 3) as first_3_char,
	RIGHT(ENAME, 3) as last_3_char
FROM EMP

-- 36th Question
SELECT 
	ENAME,
	REPLACE(ENAME, 'A', 'a') as replace_ENAME
FROM EMP

-- 37th Question
SELECT 
	ENAME
FROM EMP
WHERE ENAME LIKE '%AR%'

-- 38th Question

-- 39th Question

-- 40th Question => DATEADD function takes 3 args (Interval, increment int, expression/column)
SELECT 
	ENAME,
	DATEADD(YEAR, 3, HIREDATE) AS THREE_YEARS_DATE_AFTER_HIRE
FROM EMP

SELECT * FROM EMP

-- 41st Question
SELECT
	ENAME,
	HIREDATE,
	DATEDIFF(day, HIREDATE, GETDATE()) as DAYS_PASSED_AFTER_JOINING
FROM EMP

-- 42nd Question
SELECT 
	ENAME,
	HIREDATE,
	DATEDIFF(month, HIREDATE, GETDATE()) as MONTHS_PASSED_AFTER_JOINING
FROM EMP

-- 43rd Question
SELECT *
FROM EMP
ORDER BY ENAME ASC

-- 44th Question
SELECT 
	ENAME,
	HIREDATE 
FROM EMP
ORDER BY HIREDATE ASC 

-- 45th Question
SELECT 
	ENAME,
	JOB,
	SAL
FROM EMP
ORDER BY JOB ASC, SAL DESC

-- 46th Question

-- 47th Question


-- 48th Question
SELECT 
	ENAME,
	JOB,
	SAL
FROM EMP
WHERE COMM = 0 OR COMM IS NULL
ORDER BY JOB ASC

-- 49th Question
SELECT 
	ENAME,
	JOB,
	HIREDATE
FROM EMP
WHERE YEAR(HIREDATE) = '2003' 
ORDER BY HIREDATE ASC

-- 50th Question
